# Site settings
title: Are all hospital closures bad?
tag_text: 
description: 
 


# Build settings
markdown: kramdown
baseurl: "http://users.nber.org/~daltonm/hclose/"
url: "http://users.nber.org/~daltonm/hclose/"
permalink: /:categories/:title/
exclude: ["README.md"]


